apiVersion: procedure.snowflake.m.bronze-deer.de/v1alpha1
kind: ProcedurePython
metadata:
  annotations:
    meta.upbound.io/example-id: procedure/v1alpha1/procedurepython
  labels:
    testing.upbound.io/example-name: w
  name: w
  namespace: crossplane-system
spec:
  forProvider:
    arguments:
    - argDataType: VARCHAR(100)
      argName: x
    databaseSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    handler: echoVarchar
    name: Name
    procedureDefinition: |2
        def echoVarchar(x):
        result = ''
        for a in range(5):
          result += x
        return result
    returnType: VARCHAR(100)
    runtimeVersion: "3.9"
    schemaSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    snowparkPackage: 1.14.0
