// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type AccountRolePrivilegeGrantInitParameters struct {

	// (String) The fully qualified name of the account role to which privileges will be granted. For more information about this resource, see docs.
	// The fully qualified name of the account role to which privileges will be granted. For more information about this resource, see [docs](./account_role).
	// +crossplane:generate:reference:type=github.com/BronzeDeer/provider-snowflake/apis/cluster/rbac/v1alpha1.AccountRole
	AccountRoleName *string `json:"accountRoleName,omitempty" tf:"account_role_name,omitempty"`

	// Reference to a AccountRole in rbac to populate accountRoleName.
	// +kubebuilder:validation:Optional
	AccountRoleNameRef *v1.Reference `json:"accountRoleNameRef,omitempty" tf:"-"`

	// Selector for a AccountRole in rbac to populate accountRoleName.
	// +kubebuilder:validation:Optional
	AccountRoleNameSelector *v1.Selector `json:"accountRoleNameSelector,omitempty" tf:"-"`

	// (Boolean) (Default: false) Grant all privileges on the account role. When all privileges cannot be granted, the provider returns a warning, which is aligned with the Snowsight behavior.
	// (Default: `false`) Grant all privileges on the account role. When all privileges cannot be granted, the provider returns a warning, which is aligned with the Snowsight behavior.
	AllPrivileges *bool `json:"allPrivileges,omitempty" tf:"all_privileges,omitempty"`

	// grant defined privileges. It is supposed to be used only in “grant privileges on all X’s in database / schema Y” or “grant all privileges to X” scenarios to make sure that every new object in a given database / schema is granted by the account role and every new privilege is granted to the database role.
	// (Default: `false`) If true, the resource will always produce a “plan” and on “apply” it will re-grant defined privileges. It is supposed to be used only in “grant privileges on all X’s in database / schema Y” or “grant all privileges to X” scenarios to make sure that every new object in a given database / schema is granted by the account role and every new privilege is granted to the database role.
	AlwaysApply *bool `json:"alwaysApply,omitempty" tf:"always_apply,omitempty"`

	// (String) (Default: “) This is a helper field and should not be set. Its main purpose is to help to achieve the functionality described by the always_apply field.
	// (Default: “) This is a helper field and should not be set. Its main purpose is to help to achieve the functionality described by the always_apply field.
	AlwaysApplyTrigger *string `json:"alwaysApplyTrigger,omitempty" tf:"always_apply_trigger,omitempty"`

	// (Boolean) (Default: false) If true, the privileges will be granted on the account.
	// (Default: `false`) If true, the privileges will be granted on the account.
	OnAccount *bool `json:"onAccount,omitempty" tf:"on_account,omitempty"`

	// (Block List, Max: 1) Specifies the account object on which privileges will be granted (see below for nested schema)
	// Specifies the account object on which privileges will be granted
	OnAccountObject []OnAccountObjectInitParameters `json:"onAccountObject,omitempty" tf:"on_account_object,omitempty"`

	// (Block List, Max: 1) Specifies the schema on which privileges will be granted. (see below for nested schema)
	// Specifies the schema on which privileges will be granted.
	OnSchema []OnSchemaInitParameters `json:"onSchema,omitempty" tf:"on_schema,omitempty"`

	// (Block List, Max: 1) Specifies the schema object on which privileges will be granted. (see below for nested schema)
	// Specifies the schema object on which privileges will be granted.
	OnSchemaObject []OnSchemaObjectInitParameters `json:"onSchemaObject,omitempty" tf:"on_schema_object,omitempty"`

	// sensitive; use only upper-case privileges.
	// The privileges to grant on the account role. This field is case-sensitive; use only upper-case privileges.
	// +listType=set
	Privileges []*string `json:"privileges,omitempty" tf:"privileges,omitempty"`

	// (Boolean) (Default: false) If true, the resource will revoke all privileges that are not explicitly defined in the config making it a central source of truth for the privileges granted on an object to an account role. If false, the resource will be only concerned with the privileges that are explicitly defined in the config. This means, the flag update doesn't revoke immediately any externally granted privileges.g., revoking privileges not specified in the configuration) in the plan. External privileges will be detected regardless of their grant option. The parameter can be only used when GRANTS_STRICT_PRIVILEGE_MANAGEMENT option is specified in provider block in the experimental_features_enabled field. Regular and future grants are treated separately, meaning, more resources need to be defined to control regular and future grants for a given object and role (and for a given database or schema they're defined in for future grants). See our Strict privilege management guide for more information.
	// (Default: `false`) If true, the resource will revoke all privileges that are not explicitly defined in the config making it a central source of truth for the privileges granted on an object to an account role. If false, the resource will be only concerned with the privileges that are explicitly defined in the config. This means, the flag update doesn't revoke immediately any externally granted privileges.g., revoking privileges not specified in the configuration) in the plan. External privileges will be detected regardless of their grant option. The parameter can be only used when `GRANTS_STRICT_PRIVILEGE_MANAGEMENT` option is specified in provider block in the [`experimental_features_enabled`](https://registry.io/providers/snowflakedb/snowflake/latest/docs#experimental_features_enabled-1) field. Regular and future grants are treated separately, meaning, more resources need to be defined to control regular and future grants for a given object and role (and for a given database or schema they're defined in for future grants). See our [Strict privilege management](https://registry.io/providers/snowflakedb/snowflake/latest/docs/guides/strict_privilege_management) guide for more information.
	StrictPrivilegeManagement *bool `json:"strictPrivilegeManagement,omitempty" tf:"strict_privilege_management,omitempty"`

	// (Boolean) (Default: false) Specifies whether the grantee can grant the privileges to other users.
	// (Default: `false`) Specifies whether the grantee can grant the privileges to other users.
	WithGrantOption *bool `json:"withGrantOption,omitempty" tf:"with_grant_option,omitempty"`
}

type AccountRolePrivilegeGrantObservation struct {

	// (String) The fully qualified name of the account role to which privileges will be granted. For more information about this resource, see docs.
	// The fully qualified name of the account role to which privileges will be granted. For more information about this resource, see [docs](./account_role).
	AccountRoleName *string `json:"accountRoleName,omitempty" tf:"account_role_name,omitempty"`

	// (Boolean) (Default: false) Grant all privileges on the account role. When all privileges cannot be granted, the provider returns a warning, which is aligned with the Snowsight behavior.
	// (Default: `false`) Grant all privileges on the account role. When all privileges cannot be granted, the provider returns a warning, which is aligned with the Snowsight behavior.
	AllPrivileges *bool `json:"allPrivileges,omitempty" tf:"all_privileges,omitempty"`

	// grant defined privileges. It is supposed to be used only in “grant privileges on all X’s in database / schema Y” or “grant all privileges to X” scenarios to make sure that every new object in a given database / schema is granted by the account role and every new privilege is granted to the database role.
	// (Default: `false`) If true, the resource will always produce a “plan” and on “apply” it will re-grant defined privileges. It is supposed to be used only in “grant privileges on all X’s in database / schema Y” or “grant all privileges to X” scenarios to make sure that every new object in a given database / schema is granted by the account role and every new privilege is granted to the database role.
	AlwaysApply *bool `json:"alwaysApply,omitempty" tf:"always_apply,omitempty"`

	// (String) (Default: “) This is a helper field and should not be set. Its main purpose is to help to achieve the functionality described by the always_apply field.
	// (Default: “) This is a helper field and should not be set. Its main purpose is to help to achieve the functionality described by the always_apply field.
	AlwaysApplyTrigger *string `json:"alwaysApplyTrigger,omitempty" tf:"always_apply_trigger,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (Boolean) (Default: false) If true, the privileges will be granted on the account.
	// (Default: `false`) If true, the privileges will be granted on the account.
	OnAccount *bool `json:"onAccount,omitempty" tf:"on_account,omitempty"`

	// (Block List, Max: 1) Specifies the account object on which privileges will be granted (see below for nested schema)
	// Specifies the account object on which privileges will be granted
	OnAccountObject []OnAccountObjectObservation `json:"onAccountObject,omitempty" tf:"on_account_object,omitempty"`

	// (Block List, Max: 1) Specifies the schema on which privileges will be granted. (see below for nested schema)
	// Specifies the schema on which privileges will be granted.
	OnSchema []OnSchemaObservation `json:"onSchema,omitempty" tf:"on_schema,omitempty"`

	// (Block List, Max: 1) Specifies the schema object on which privileges will be granted. (see below for nested schema)
	// Specifies the schema object on which privileges will be granted.
	OnSchemaObject []OnSchemaObjectObservation `json:"onSchemaObject,omitempty" tf:"on_schema_object,omitempty"`

	// sensitive; use only upper-case privileges.
	// The privileges to grant on the account role. This field is case-sensitive; use only upper-case privileges.
	// +listType=set
	Privileges []*string `json:"privileges,omitempty" tf:"privileges,omitempty"`

	// (Boolean) (Default: false) If true, the resource will revoke all privileges that are not explicitly defined in the config making it a central source of truth for the privileges granted on an object to an account role. If false, the resource will be only concerned with the privileges that are explicitly defined in the config. This means, the flag update doesn't revoke immediately any externally granted privileges.g., revoking privileges not specified in the configuration) in the plan. External privileges will be detected regardless of their grant option. The parameter can be only used when GRANTS_STRICT_PRIVILEGE_MANAGEMENT option is specified in provider block in the experimental_features_enabled field. Regular and future grants are treated separately, meaning, more resources need to be defined to control regular and future grants for a given object and role (and for a given database or schema they're defined in for future grants). See our Strict privilege management guide for more information.
	// (Default: `false`) If true, the resource will revoke all privileges that are not explicitly defined in the config making it a central source of truth for the privileges granted on an object to an account role. If false, the resource will be only concerned with the privileges that are explicitly defined in the config. This means, the flag update doesn't revoke immediately any externally granted privileges.g., revoking privileges not specified in the configuration) in the plan. External privileges will be detected regardless of their grant option. The parameter can be only used when `GRANTS_STRICT_PRIVILEGE_MANAGEMENT` option is specified in provider block in the [`experimental_features_enabled`](https://registry.io/providers/snowflakedb/snowflake/latest/docs#experimental_features_enabled-1) field. Regular and future grants are treated separately, meaning, more resources need to be defined to control regular and future grants for a given object and role (and for a given database or schema they're defined in for future grants). See our [Strict privilege management](https://registry.io/providers/snowflakedb/snowflake/latest/docs/guides/strict_privilege_management) guide for more information.
	StrictPrivilegeManagement *bool `json:"strictPrivilegeManagement,omitempty" tf:"strict_privilege_management,omitempty"`

	// (Boolean) (Default: false) Specifies whether the grantee can grant the privileges to other users.
	// (Default: `false`) Specifies whether the grantee can grant the privileges to other users.
	WithGrantOption *bool `json:"withGrantOption,omitempty" tf:"with_grant_option,omitempty"`
}

type AccountRolePrivilegeGrantParameters struct {

	// (String) The fully qualified name of the account role to which privileges will be granted. For more information about this resource, see docs.
	// The fully qualified name of the account role to which privileges will be granted. For more information about this resource, see [docs](./account_role).
	// +crossplane:generate:reference:type=github.com/BronzeDeer/provider-snowflake/apis/cluster/rbac/v1alpha1.AccountRole
	// +kubebuilder:validation:Optional
	AccountRoleName *string `json:"accountRoleName,omitempty" tf:"account_role_name,omitempty"`

	// Reference to a AccountRole in rbac to populate accountRoleName.
	// +kubebuilder:validation:Optional
	AccountRoleNameRef *v1.Reference `json:"accountRoleNameRef,omitempty" tf:"-"`

	// Selector for a AccountRole in rbac to populate accountRoleName.
	// +kubebuilder:validation:Optional
	AccountRoleNameSelector *v1.Selector `json:"accountRoleNameSelector,omitempty" tf:"-"`

	// (Boolean) (Default: false) Grant all privileges on the account role. When all privileges cannot be granted, the provider returns a warning, which is aligned with the Snowsight behavior.
	// (Default: `false`) Grant all privileges on the account role. When all privileges cannot be granted, the provider returns a warning, which is aligned with the Snowsight behavior.
	// +kubebuilder:validation:Optional
	AllPrivileges *bool `json:"allPrivileges,omitempty" tf:"all_privileges,omitempty"`

	// grant defined privileges. It is supposed to be used only in “grant privileges on all X’s in database / schema Y” or “grant all privileges to X” scenarios to make sure that every new object in a given database / schema is granted by the account role and every new privilege is granted to the database role.
	// (Default: `false`) If true, the resource will always produce a “plan” and on “apply” it will re-grant defined privileges. It is supposed to be used only in “grant privileges on all X’s in database / schema Y” or “grant all privileges to X” scenarios to make sure that every new object in a given database / schema is granted by the account role and every new privilege is granted to the database role.
	// +kubebuilder:validation:Optional
	AlwaysApply *bool `json:"alwaysApply,omitempty" tf:"always_apply,omitempty"`

	// (String) (Default: “) This is a helper field and should not be set. Its main purpose is to help to achieve the functionality described by the always_apply field.
	// (Default: “) This is a helper field and should not be set. Its main purpose is to help to achieve the functionality described by the always_apply field.
	// +kubebuilder:validation:Optional
	AlwaysApplyTrigger *string `json:"alwaysApplyTrigger,omitempty" tf:"always_apply_trigger,omitempty"`

	// (Boolean) (Default: false) If true, the privileges will be granted on the account.
	// (Default: `false`) If true, the privileges will be granted on the account.
	// +kubebuilder:validation:Optional
	OnAccount *bool `json:"onAccount,omitempty" tf:"on_account,omitempty"`

	// (Block List, Max: 1) Specifies the account object on which privileges will be granted (see below for nested schema)
	// Specifies the account object on which privileges will be granted
	// +kubebuilder:validation:Optional
	OnAccountObject []OnAccountObjectParameters `json:"onAccountObject,omitempty" tf:"on_account_object,omitempty"`

	// (Block List, Max: 1) Specifies the schema on which privileges will be granted. (see below for nested schema)
	// Specifies the schema on which privileges will be granted.
	// +kubebuilder:validation:Optional
	OnSchema []OnSchemaParameters `json:"onSchema,omitempty" tf:"on_schema,omitempty"`

	// (Block List, Max: 1) Specifies the schema object on which privileges will be granted. (see below for nested schema)
	// Specifies the schema object on which privileges will be granted.
	// +kubebuilder:validation:Optional
	OnSchemaObject []OnSchemaObjectParameters `json:"onSchemaObject,omitempty" tf:"on_schema_object,omitempty"`

	// sensitive; use only upper-case privileges.
	// The privileges to grant on the account role. This field is case-sensitive; use only upper-case privileges.
	// +kubebuilder:validation:Optional
	// +listType=set
	Privileges []*string `json:"privileges,omitempty" tf:"privileges,omitempty"`

	// (Boolean) (Default: false) If true, the resource will revoke all privileges that are not explicitly defined in the config making it a central source of truth for the privileges granted on an object to an account role. If false, the resource will be only concerned with the privileges that are explicitly defined in the config. This means, the flag update doesn't revoke immediately any externally granted privileges.g., revoking privileges not specified in the configuration) in the plan. External privileges will be detected regardless of their grant option. The parameter can be only used when GRANTS_STRICT_PRIVILEGE_MANAGEMENT option is specified in provider block in the experimental_features_enabled field. Regular and future grants are treated separately, meaning, more resources need to be defined to control regular and future grants for a given object and role (and for a given database or schema they're defined in for future grants). See our Strict privilege management guide for more information.
	// (Default: `false`) If true, the resource will revoke all privileges that are not explicitly defined in the config making it a central source of truth for the privileges granted on an object to an account role. If false, the resource will be only concerned with the privileges that are explicitly defined in the config. This means, the flag update doesn't revoke immediately any externally granted privileges.g., revoking privileges not specified in the configuration) in the plan. External privileges will be detected regardless of their grant option. The parameter can be only used when `GRANTS_STRICT_PRIVILEGE_MANAGEMENT` option is specified in provider block in the [`experimental_features_enabled`](https://registry.io/providers/snowflakedb/snowflake/latest/docs#experimental_features_enabled-1) field. Regular and future grants are treated separately, meaning, more resources need to be defined to control regular and future grants for a given object and role (and for a given database or schema they're defined in for future grants). See our [Strict privilege management](https://registry.io/providers/snowflakedb/snowflake/latest/docs/guides/strict_privilege_management) guide for more information.
	// +kubebuilder:validation:Optional
	StrictPrivilegeManagement *bool `json:"strictPrivilegeManagement,omitempty" tf:"strict_privilege_management,omitempty"`

	// (Boolean) (Default: false) Specifies whether the grantee can grant the privileges to other users.
	// (Default: `false`) Specifies whether the grantee can grant the privileges to other users.
	// +kubebuilder:validation:Optional
	WithGrantOption *bool `json:"withGrantOption,omitempty" tf:"with_grant_option,omitempty"`
}

type AllInitParameters struct {

	// (String) The fully qualified name of the database in which the inherited privilege will be granted on all schemas.
	InDatabase *string `json:"inDatabase,omitempty" tf:"in_database,omitempty"`

	// (String)
	InSchema *string `json:"inSchema,omitempty" tf:"in_schema,omitempty"`

	// insensitive): USERS | RESOURCE MONITORS | WAREHOUSES | COMPUTE POOLS | DATABASES | INTEGRATIONS | CONNECTIONS | FAILOVER GROUPS | REPLICATION GROUPS | EXTERNAL VOLUMES. Snowflake validates the type at apply time.
	// The plural object type of the schema object on which privileges will be granted. For more information head over to [Snowflake documentation](https://docs.snowflake.com/en/sql-reference/sql/grant-privilege#required-parameters). Known examples (case-insensitive): `AGENTS` | `AGGREGATION POLICIES` | `ALERTS` | `AUTHENTICATION POLICIES` | `CORTEX SEARCH SERVICES` | `DATA METRIC FUNCTIONS` | `DATASETS` | `DBT PROJECTS` | `DYNAMIC TABLES` | `EVENT TABLES` | `EXPERIMENTS` | `EXTERNAL TABLES` | `FILE FORMATS` | `FUNCTIONS` | `GIT REPOSITORIES` | `HYBRID TABLES` | `IMAGE REPOSITORIES` | `ICEBERG TABLES` | `INTERACTIVE TABLES` | `MASKING POLICIES` | `MATERIALIZED VIEWS` | `MCP SERVERS` | `MODELS` | `MODEL MONITORS` | `NETWORK RULES` | `NOTEBOOKS` | `ONLINE FEATURE TABLES` | `PACKAGES POLICIES` | `PASSWORD POLICIES` | `PIPES` | `PRIVACY POLICIES` | `PROCEDURES` | `PROJECTION POLICIES` | `ROW ACCESS POLICIES` | `SECRETS` | `SEMANTIC VIEWS` | `SERVICES` | `SESSION POLICIES` | `SEQUENCES` | `SNAPSHOTS` | `SNAPSHOT POLICIES` | `SNAPSHOT SETS` | `STAGES` | `STREAMS` | `STREAMLITS` | `TABLES` | `TAGS` | `TASKS` | `VIEWS` | `WORKSPACES`. Snowflake validates the type at apply time.
	ObjectTypePlural *string `json:"objectTypePlural,omitempty" tf:"object_type_plural,omitempty"`
}

type AllObservation struct {

	// (String) The fully qualified name of the database in which the inherited privilege will be granted on all schemas.
	InDatabase *string `json:"inDatabase,omitempty" tf:"in_database,omitempty"`

	// (String)
	InSchema *string `json:"inSchema,omitempty" tf:"in_schema,omitempty"`

	// insensitive): USERS | RESOURCE MONITORS | WAREHOUSES | COMPUTE POOLS | DATABASES | INTEGRATIONS | CONNECTIONS | FAILOVER GROUPS | REPLICATION GROUPS | EXTERNAL VOLUMES. Snowflake validates the type at apply time.
	// The plural object type of the schema object on which privileges will be granted. For more information head over to [Snowflake documentation](https://docs.snowflake.com/en/sql-reference/sql/grant-privilege#required-parameters). Known examples (case-insensitive): `AGENTS` | `AGGREGATION POLICIES` | `ALERTS` | `AUTHENTICATION POLICIES` | `CORTEX SEARCH SERVICES` | `DATA METRIC FUNCTIONS` | `DATASETS` | `DBT PROJECTS` | `DYNAMIC TABLES` | `EVENT TABLES` | `EXPERIMENTS` | `EXTERNAL TABLES` | `FILE FORMATS` | `FUNCTIONS` | `GIT REPOSITORIES` | `HYBRID TABLES` | `IMAGE REPOSITORIES` | `ICEBERG TABLES` | `INTERACTIVE TABLES` | `MASKING POLICIES` | `MATERIALIZED VIEWS` | `MCP SERVERS` | `MODELS` | `MODEL MONITORS` | `NETWORK RULES` | `NOTEBOOKS` | `ONLINE FEATURE TABLES` | `PACKAGES POLICIES` | `PASSWORD POLICIES` | `PIPES` | `PRIVACY POLICIES` | `PROCEDURES` | `PROJECTION POLICIES` | `ROW ACCESS POLICIES` | `SECRETS` | `SEMANTIC VIEWS` | `SERVICES` | `SESSION POLICIES` | `SEQUENCES` | `SNAPSHOTS` | `SNAPSHOT POLICIES` | `SNAPSHOT SETS` | `STAGES` | `STREAMS` | `STREAMLITS` | `TABLES` | `TAGS` | `TASKS` | `VIEWS` | `WORKSPACES`. Snowflake validates the type at apply time.
	ObjectTypePlural *string `json:"objectTypePlural,omitempty" tf:"object_type_plural,omitempty"`
}

type AllParameters struct {

	// (String) The fully qualified name of the database in which the inherited privilege will be granted on all schemas.
	// +kubebuilder:validation:Optional
	InDatabase *string `json:"inDatabase,omitempty" tf:"in_database,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	InSchema *string `json:"inSchema,omitempty" tf:"in_schema,omitempty"`

	// insensitive): USERS | RESOURCE MONITORS | WAREHOUSES | COMPUTE POOLS | DATABASES | INTEGRATIONS | CONNECTIONS | FAILOVER GROUPS | REPLICATION GROUPS | EXTERNAL VOLUMES. Snowflake validates the type at apply time.
	// The plural object type of the schema object on which privileges will be granted. For more information head over to [Snowflake documentation](https://docs.snowflake.com/en/sql-reference/sql/grant-privilege#required-parameters). Known examples (case-insensitive): `AGENTS` | `AGGREGATION POLICIES` | `ALERTS` | `AUTHENTICATION POLICIES` | `CORTEX SEARCH SERVICES` | `DATA METRIC FUNCTIONS` | `DATASETS` | `DBT PROJECTS` | `DYNAMIC TABLES` | `EVENT TABLES` | `EXPERIMENTS` | `EXTERNAL TABLES` | `FILE FORMATS` | `FUNCTIONS` | `GIT REPOSITORIES` | `HYBRID TABLES` | `IMAGE REPOSITORIES` | `ICEBERG TABLES` | `INTERACTIVE TABLES` | `MASKING POLICIES` | `MATERIALIZED VIEWS` | `MCP SERVERS` | `MODELS` | `MODEL MONITORS` | `NETWORK RULES` | `NOTEBOOKS` | `ONLINE FEATURE TABLES` | `PACKAGES POLICIES` | `PASSWORD POLICIES` | `PIPES` | `PRIVACY POLICIES` | `PROCEDURES` | `PROJECTION POLICIES` | `ROW ACCESS POLICIES` | `SECRETS` | `SEMANTIC VIEWS` | `SERVICES` | `SESSION POLICIES` | `SEQUENCES` | `SNAPSHOTS` | `SNAPSHOT POLICIES` | `SNAPSHOT SETS` | `STAGES` | `STREAMS` | `STREAMLITS` | `TABLES` | `TAGS` | `TASKS` | `VIEWS` | `WORKSPACES`. Snowflake validates the type at apply time.
	// +kubebuilder:validation:Optional
	ObjectTypePlural *string `json:"objectTypePlural" tf:"object_type_plural,omitempty"`
}

type FutureInitParameters struct {

	// (String) The fully qualified name of the database in which the inherited privilege will be granted on all schemas.
	InDatabase *string `json:"inDatabase,omitempty" tf:"in_database,omitempty"`

	// (String)
	InSchema *string `json:"inSchema,omitempty" tf:"in_schema,omitempty"`

	// insensitive): USERS | RESOURCE MONITORS | WAREHOUSES | COMPUTE POOLS | DATABASES | INTEGRATIONS | CONNECTIONS | FAILOVER GROUPS | REPLICATION GROUPS | EXTERNAL VOLUMES. Snowflake validates the type at apply time.
	// The plural object type of the schema object on which privileges will be granted. For more information head over to [Snowflake documentation](https://docs.snowflake.com/en/sql-reference/sql/grant-privilege#required-parameters). Known examples (case-insensitive): `AGENTS` | `ALERTS` | `AUTHENTICATION POLICIES` | `CORTEX SEARCH SERVICES` | `DATA METRIC FUNCTIONS` | `DATASETS` | `DBT PROJECTS` | `DYNAMIC TABLES` | `EVENT TABLES` | `EXTERNAL TABLES` | `FILE FORMATS` | `FUNCTIONS` | `GIT REPOSITORIES` | `HYBRID TABLES` | `IMAGE REPOSITORIES` | `ICEBERG TABLES` | `INTERACTIVE TABLES` | `MATERIALIZED VIEWS` | `MCP SERVERS` | `MODELS` | `MODEL MONITORS` | `NETWORK RULES` | `NOTEBOOKS` | `ONLINE FEATURE TABLES` | `PASSWORD POLICIES` | `PIPES` | `PRIVACY POLICIES` | `PROCEDURES` | `SECRETS` | `SEMANTIC VIEWS` | `SERVICES` | `SEQUENCES` | `SNAPSHOT POLICIES` | `SNAPSHOT SETS` | `STAGES` | `STREAMS` | `STREAMLITS` | `TABLES` | `TASKS` | `VIEWS` | `WORKSPACES`. Snowflake validates the type at apply time.
	ObjectTypePlural *string `json:"objectTypePlural,omitempty" tf:"object_type_plural,omitempty"`
}

type FutureObservation struct {

	// (String) The fully qualified name of the database in which the inherited privilege will be granted on all schemas.
	InDatabase *string `json:"inDatabase,omitempty" tf:"in_database,omitempty"`

	// (String)
	InSchema *string `json:"inSchema,omitempty" tf:"in_schema,omitempty"`

	// insensitive): USERS | RESOURCE MONITORS | WAREHOUSES | COMPUTE POOLS | DATABASES | INTEGRATIONS | CONNECTIONS | FAILOVER GROUPS | REPLICATION GROUPS | EXTERNAL VOLUMES. Snowflake validates the type at apply time.
	// The plural object type of the schema object on which privileges will be granted. For more information head over to [Snowflake documentation](https://docs.snowflake.com/en/sql-reference/sql/grant-privilege#required-parameters). Known examples (case-insensitive): `AGENTS` | `ALERTS` | `AUTHENTICATION POLICIES` | `CORTEX SEARCH SERVICES` | `DATA METRIC FUNCTIONS` | `DATASETS` | `DBT PROJECTS` | `DYNAMIC TABLES` | `EVENT TABLES` | `EXTERNAL TABLES` | `FILE FORMATS` | `FUNCTIONS` | `GIT REPOSITORIES` | `HYBRID TABLES` | `IMAGE REPOSITORIES` | `ICEBERG TABLES` | `INTERACTIVE TABLES` | `MATERIALIZED VIEWS` | `MCP SERVERS` | `MODELS` | `MODEL MONITORS` | `NETWORK RULES` | `NOTEBOOKS` | `ONLINE FEATURE TABLES` | `PASSWORD POLICIES` | `PIPES` | `PRIVACY POLICIES` | `PROCEDURES` | `SECRETS` | `SEMANTIC VIEWS` | `SERVICES` | `SEQUENCES` | `SNAPSHOT POLICIES` | `SNAPSHOT SETS` | `STAGES` | `STREAMS` | `STREAMLITS` | `TABLES` | `TASKS` | `VIEWS` | `WORKSPACES`. Snowflake validates the type at apply time.
	ObjectTypePlural *string `json:"objectTypePlural,omitempty" tf:"object_type_plural,omitempty"`
}

type FutureParameters struct {

	// (String) The fully qualified name of the database in which the inherited privilege will be granted on all schemas.
	// +kubebuilder:validation:Optional
	InDatabase *string `json:"inDatabase,omitempty" tf:"in_database,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	InSchema *string `json:"inSchema,omitempty" tf:"in_schema,omitempty"`

	// insensitive): USERS | RESOURCE MONITORS | WAREHOUSES | COMPUTE POOLS | DATABASES | INTEGRATIONS | CONNECTIONS | FAILOVER GROUPS | REPLICATION GROUPS | EXTERNAL VOLUMES. Snowflake validates the type at apply time.
	// The plural object type of the schema object on which privileges will be granted. For more information head over to [Snowflake documentation](https://docs.snowflake.com/en/sql-reference/sql/grant-privilege#required-parameters). Known examples (case-insensitive): `AGENTS` | `ALERTS` | `AUTHENTICATION POLICIES` | `CORTEX SEARCH SERVICES` | `DATA METRIC FUNCTIONS` | `DATASETS` | `DBT PROJECTS` | `DYNAMIC TABLES` | `EVENT TABLES` | `EXTERNAL TABLES` | `FILE FORMATS` | `FUNCTIONS` | `GIT REPOSITORIES` | `HYBRID TABLES` | `IMAGE REPOSITORIES` | `ICEBERG TABLES` | `INTERACTIVE TABLES` | `MATERIALIZED VIEWS` | `MCP SERVERS` | `MODELS` | `MODEL MONITORS` | `NETWORK RULES` | `NOTEBOOKS` | `ONLINE FEATURE TABLES` | `PASSWORD POLICIES` | `PIPES` | `PRIVACY POLICIES` | `PROCEDURES` | `SECRETS` | `SEMANTIC VIEWS` | `SERVICES` | `SEQUENCES` | `SNAPSHOT POLICIES` | `SNAPSHOT SETS` | `STAGES` | `STREAMS` | `STREAMLITS` | `TABLES` | `TASKS` | `VIEWS` | `WORKSPACES`. Snowflake validates the type at apply time.
	// +kubebuilder:validation:Optional
	ObjectTypePlural *string `json:"objectTypePlural" tf:"object_type_plural,omitempty"`
}

type InheritedInitParameters struct {

	// insensitive): USERS | RESOURCE MONITORS | WAREHOUSES | COMPUTE POOLS | DATABASES | INTEGRATIONS | CONNECTIONS | FAILOVER GROUPS | REPLICATION GROUPS | EXTERNAL VOLUMES. Snowflake validates the type at apply time.
	// The plural object type of the account object on which an inherited privilege will be granted. For more information head over to [Snowflake documentation](https://docs.snowflake.com/en/sql-reference/sql/grant-privilege#required-parameters). Known examples (case-insensitive): `USERS` | `RESOURCE MONITORS` | `WAREHOUSES` | `COMPUTE POOLS` | `DATABASES` | `INTEGRATIONS` | `CONNECTIONS` | `FAILOVER GROUPS` | `REPLICATION GROUPS` | `EXTERNAL VOLUMES`. Snowflake validates the type at apply time.
	ObjectTypePlural *string `json:"objectTypePlural,omitempty" tf:"object_type_plural,omitempty"`
}

type InheritedObservation struct {

	// insensitive): USERS | RESOURCE MONITORS | WAREHOUSES | COMPUTE POOLS | DATABASES | INTEGRATIONS | CONNECTIONS | FAILOVER GROUPS | REPLICATION GROUPS | EXTERNAL VOLUMES. Snowflake validates the type at apply time.
	// The plural object type of the account object on which an inherited privilege will be granted. For more information head over to [Snowflake documentation](https://docs.snowflake.com/en/sql-reference/sql/grant-privilege#required-parameters). Known examples (case-insensitive): `USERS` | `RESOURCE MONITORS` | `WAREHOUSES` | `COMPUTE POOLS` | `DATABASES` | `INTEGRATIONS` | `CONNECTIONS` | `FAILOVER GROUPS` | `REPLICATION GROUPS` | `EXTERNAL VOLUMES`. Snowflake validates the type at apply time.
	ObjectTypePlural *string `json:"objectTypePlural,omitempty" tf:"object_type_plural,omitempty"`
}

type InheritedParameters struct {

	// insensitive): USERS | RESOURCE MONITORS | WAREHOUSES | COMPUTE POOLS | DATABASES | INTEGRATIONS | CONNECTIONS | FAILOVER GROUPS | REPLICATION GROUPS | EXTERNAL VOLUMES. Snowflake validates the type at apply time.
	// The plural object type of the account object on which an inherited privilege will be granted. For more information head over to [Snowflake documentation](https://docs.snowflake.com/en/sql-reference/sql/grant-privilege#required-parameters). Known examples (case-insensitive): `USERS` | `RESOURCE MONITORS` | `WAREHOUSES` | `COMPUTE POOLS` | `DATABASES` | `INTEGRATIONS` | `CONNECTIONS` | `FAILOVER GROUPS` | `REPLICATION GROUPS` | `EXTERNAL VOLUMES`. Snowflake validates the type at apply time.
	// +kubebuilder:validation:Optional
	ObjectTypePlural *string `json:"objectTypePlural" tf:"object_type_plural,omitempty"`
}

type OnAccountObjectInitParameters struct {

	// (Block List, Max: 1) Configures an inherited privilege to be granted on all current and future account objects of a given type in the account. See Inherited grants for more details. This field can be only used when INHERITED_GRANTS option is specified in provider block in the experimental_features_enabled field. (see below for nested schema)
	// Configures an inherited privilege to be granted on all current and future account objects of a given type in the account. See [Inherited grants](https://docs.snowflake.com/en/user-guide/inherited-grants-using) for more details. This field can be only used when `INHERITED_GRANTS` option is specified in provider block in the [`experimental_features_enabled`](../#experimental_features_enabled-1) field.
	Inherited []InheritedInitParameters `json:"inherited,omitempty" tf:"inherited,omitempty"`

	// (String) The fully qualified name of the object on which privileges will be granted.
	// The fully qualified name of the object on which privileges will be granted.
	ObjectName *string `json:"objectName,omitempty" tf:"object_name,omitempty"`

	// insensitive): USER | RESOURCE MONITOR | WAREHOUSE | COMPUTE POOL | DATABASE | INTEGRATION | CONNECTION | FAILOVER GROUP | REPLICATION GROUP | EXTERNAL VOLUME | SNOWFLAKE INTELLIGENCE. Snowflake validates the type at apply time.
	// The object type of the account object on which privileges will be granted. For more information head over to [Snowflake documentation](https://docs.snowflake.com/en/sql-reference/sql/grant-privilege#required-parameters). Known examples (case-insensitive): `USER` | `RESOURCE MONITOR` | `WAREHOUSE` | `COMPUTE POOL` | `DATABASE` | `INTEGRATION` | `CONNECTION` | `FAILOVER GROUP` | `REPLICATION GROUP` | `EXTERNAL VOLUME` | `SNOWFLAKE INTELLIGENCE`. Snowflake validates the type at apply time.
	ObjectType *string `json:"objectType,omitempty" tf:"object_type,omitempty"`
}

type OnAccountObjectObservation struct {

	// (Block List, Max: 1) Configures an inherited privilege to be granted on all current and future account objects of a given type in the account. See Inherited grants for more details. This field can be only used when INHERITED_GRANTS option is specified in provider block in the experimental_features_enabled field. (see below for nested schema)
	// Configures an inherited privilege to be granted on all current and future account objects of a given type in the account. See [Inherited grants](https://docs.snowflake.com/en/user-guide/inherited-grants-using) for more details. This field can be only used when `INHERITED_GRANTS` option is specified in provider block in the [`experimental_features_enabled`](../#experimental_features_enabled-1) field.
	Inherited []InheritedObservation `json:"inherited,omitempty" tf:"inherited,omitempty"`

	// (String) The fully qualified name of the object on which privileges will be granted.
	// The fully qualified name of the object on which privileges will be granted.
	ObjectName *string `json:"objectName,omitempty" tf:"object_name,omitempty"`

	// insensitive): USER | RESOURCE MONITOR | WAREHOUSE | COMPUTE POOL | DATABASE | INTEGRATION | CONNECTION | FAILOVER GROUP | REPLICATION GROUP | EXTERNAL VOLUME | SNOWFLAKE INTELLIGENCE. Snowflake validates the type at apply time.
	// The object type of the account object on which privileges will be granted. For more information head over to [Snowflake documentation](https://docs.snowflake.com/en/sql-reference/sql/grant-privilege#required-parameters). Known examples (case-insensitive): `USER` | `RESOURCE MONITOR` | `WAREHOUSE` | `COMPUTE POOL` | `DATABASE` | `INTEGRATION` | `CONNECTION` | `FAILOVER GROUP` | `REPLICATION GROUP` | `EXTERNAL VOLUME` | `SNOWFLAKE INTELLIGENCE`. Snowflake validates the type at apply time.
	ObjectType *string `json:"objectType,omitempty" tf:"object_type,omitempty"`
}

type OnAccountObjectParameters struct {

	// (Block List, Max: 1) Configures an inherited privilege to be granted on all current and future account objects of a given type in the account. See Inherited grants for more details. This field can be only used when INHERITED_GRANTS option is specified in provider block in the experimental_features_enabled field. (see below for nested schema)
	// Configures an inherited privilege to be granted on all current and future account objects of a given type in the account. See [Inherited grants](https://docs.snowflake.com/en/user-guide/inherited-grants-using) for more details. This field can be only used when `INHERITED_GRANTS` option is specified in provider block in the [`experimental_features_enabled`](../#experimental_features_enabled-1) field.
	// +kubebuilder:validation:Optional
	Inherited []InheritedParameters `json:"inherited,omitempty" tf:"inherited,omitempty"`

	// (String) The fully qualified name of the object on which privileges will be granted.
	// The fully qualified name of the object on which privileges will be granted.
	// +kubebuilder:validation:Optional
	ObjectName *string `json:"objectName,omitempty" tf:"object_name,omitempty"`

	// insensitive): USER | RESOURCE MONITOR | WAREHOUSE | COMPUTE POOL | DATABASE | INTEGRATION | CONNECTION | FAILOVER GROUP | REPLICATION GROUP | EXTERNAL VOLUME | SNOWFLAKE INTELLIGENCE. Snowflake validates the type at apply time.
	// The object type of the account object on which privileges will be granted. For more information head over to [Snowflake documentation](https://docs.snowflake.com/en/sql-reference/sql/grant-privilege#required-parameters). Known examples (case-insensitive): `USER` | `RESOURCE MONITOR` | `WAREHOUSE` | `COMPUTE POOL` | `DATABASE` | `INTEGRATION` | `CONNECTION` | `FAILOVER GROUP` | `REPLICATION GROUP` | `EXTERNAL VOLUME` | `SNOWFLAKE INTELLIGENCE`. Snowflake validates the type at apply time.
	// +kubebuilder:validation:Optional
	ObjectType *string `json:"objectType,omitempty" tf:"object_type,omitempty"`
}

type OnSchemaInheritedInitParameters struct {

	// (Boolean) If true, the inherited privilege will be granted on all schemas in the account.
	// If true, the inherited privilege will be granted on all schemas in the account.
	InAccount *bool `json:"inAccount,omitempty" tf:"in_account,omitempty"`

	// (String) The fully qualified name of the database in which the inherited privilege will be granted on all schemas.
	// The fully qualified name of the database in which the inherited privilege will be granted on all schemas.
	InDatabase *string `json:"inDatabase,omitempty" tf:"in_database,omitempty"`
}

type OnSchemaInheritedObservation struct {

	// (Boolean) If true, the inherited privilege will be granted on all schemas in the account.
	// If true, the inherited privilege will be granted on all schemas in the account.
	InAccount *bool `json:"inAccount,omitempty" tf:"in_account,omitempty"`

	// (String) The fully qualified name of the database in which the inherited privilege will be granted on all schemas.
	// The fully qualified name of the database in which the inherited privilege will be granted on all schemas.
	InDatabase *string `json:"inDatabase,omitempty" tf:"in_database,omitempty"`
}

type OnSchemaInheritedParameters struct {

	// (Boolean) If true, the inherited privilege will be granted on all schemas in the account.
	// If true, the inherited privilege will be granted on all schemas in the account.
	// +kubebuilder:validation:Optional
	InAccount *bool `json:"inAccount,omitempty" tf:"in_account,omitempty"`

	// (String) The fully qualified name of the database in which the inherited privilege will be granted on all schemas.
	// The fully qualified name of the database in which the inherited privilege will be granted on all schemas.
	// +kubebuilder:validation:Optional
	InDatabase *string `json:"inDatabase,omitempty" tf:"in_database,omitempty"`
}

type OnSchemaInitParameters struct {

	// (String) The fully qualified name of the database.
	// The fully qualified name of the database.
	AllSchemasInDatabase *string `json:"allSchemasInDatabase,omitempty" tf:"all_schemas_in_database,omitempty"`

	// (String) The fully qualified name of the database.
	// The fully qualified name of the database.
	FutureSchemasInDatabase *string `json:"futureSchemasInDatabase,omitempty" tf:"future_schemas_in_database,omitempty"`

	// (Block List, Max: 1) Configures an inherited privilege to be granted on all current and future account objects of a given type in the account. See Inherited grants for more details. This field can be only used when INHERITED_GRANTS option is specified in provider block in the experimental_features_enabled field. (see below for nested schema)
	// Configures an inherited privilege to be granted on all current and future schemas in either the account or a database. See [Inherited grants](https://docs.snowflake.com/en/user-guide/inherited-grants-using) for more details. This field can be only used when `INHERITED_GRANTS` option is specified in provider block in the [`experimental_features_enabled`](../#experimental_features_enabled-1) field.
	Inherited []OnSchemaInheritedInitParameters `json:"inherited,omitempty" tf:"inherited,omitempty"`

	// (String) The fully qualified name of the schema.
	// The fully qualified name of the schema.
	SchemaName *string `json:"schemaName,omitempty" tf:"schema_name,omitempty"`
}

type OnSchemaObjectInheritedInitParameters struct {

	// (Boolean) If true, the inherited privilege will be granted on all schemas in the account.
	// If true, the inherited privilege will be granted on all objects of the given type in the account.
	InAccount *bool `json:"inAccount,omitempty" tf:"in_account,omitempty"`

	// (String) The fully qualified name of the database in which the inherited privilege will be granted on all schemas.
	// The fully qualified name of the database in which the inherited privilege will be granted on all objects of the given type.
	InDatabase *string `json:"inDatabase,omitempty" tf:"in_database,omitempty"`

	// (String)
	// The fully qualified name of the schema in which the inherited privilege will be granted on all objects of the given type.
	InSchema *string `json:"inSchema,omitempty" tf:"in_schema,omitempty"`

	// insensitive): USERS | RESOURCE MONITORS | WAREHOUSES | COMPUTE POOLS | DATABASES | INTEGRATIONS | CONNECTIONS | FAILOVER GROUPS | REPLICATION GROUPS | EXTERNAL VOLUMES. Snowflake validates the type at apply time.
	// The plural object type of the schema object on which an inherited privilege will be granted. For more information head over to [Snowflake documentation](https://docs.snowflake.com/en/sql-reference/sql/grant-privilege#required-parameters). Known examples (case-insensitive): `AGENTS` | `AGGREGATION POLICIES` | `ALERTS` | `AUTHENTICATION POLICIES` | `CORTEX SEARCH SERVICES` | `DATA METRIC FUNCTIONS` | `DATASETS` | `DBT PROJECTS` | `DYNAMIC TABLES` | `EVENT TABLES` | `EXPERIMENTS` | `EXTERNAL TABLES` | `FILE FORMATS` | `FUNCTIONS` | `GIT REPOSITORIES` | `HYBRID TABLES` | `IMAGE REPOSITORIES` | `ICEBERG TABLES` | `INTERACTIVE TABLES` | `MASKING POLICIES` | `MATERIALIZED VIEWS` | `MCP SERVERS` | `MODELS` | `MODEL MONITORS` | `NETWORK RULES` | `NOTEBOOKS` | `ONLINE FEATURE TABLES` | `PACKAGES POLICIES` | `PASSWORD POLICIES` | `PIPES` | `PRIVACY POLICIES` | `PROCEDURES` | `PROJECTION POLICIES` | `ROW ACCESS POLICIES` | `SECRETS` | `SEMANTIC VIEWS` | `SERVICES` | `SESSION POLICIES` | `SEQUENCES` | `SNAPSHOTS` | `SNAPSHOT POLICIES` | `SNAPSHOT SETS` | `STAGES` | `STREAMS` | `STREAMLITS` | `TABLES` | `TAGS` | `TASKS` | `VIEWS` | `WORKSPACES`. Snowflake validates the type at apply time.
	ObjectTypePlural *string `json:"objectTypePlural,omitempty" tf:"object_type_plural,omitempty"`
}

type OnSchemaObjectInheritedObservation struct {

	// (Boolean) If true, the inherited privilege will be granted on all schemas in the account.
	// If true, the inherited privilege will be granted on all objects of the given type in the account.
	InAccount *bool `json:"inAccount,omitempty" tf:"in_account,omitempty"`

	// (String) The fully qualified name of the database in which the inherited privilege will be granted on all schemas.
	// The fully qualified name of the database in which the inherited privilege will be granted on all objects of the given type.
	InDatabase *string `json:"inDatabase,omitempty" tf:"in_database,omitempty"`

	// (String)
	// The fully qualified name of the schema in which the inherited privilege will be granted on all objects of the given type.
	InSchema *string `json:"inSchema,omitempty" tf:"in_schema,omitempty"`

	// insensitive): USERS | RESOURCE MONITORS | WAREHOUSES | COMPUTE POOLS | DATABASES | INTEGRATIONS | CONNECTIONS | FAILOVER GROUPS | REPLICATION GROUPS | EXTERNAL VOLUMES. Snowflake validates the type at apply time.
	// The plural object type of the schema object on which an inherited privilege will be granted. For more information head over to [Snowflake documentation](https://docs.snowflake.com/en/sql-reference/sql/grant-privilege#required-parameters). Known examples (case-insensitive): `AGENTS` | `AGGREGATION POLICIES` | `ALERTS` | `AUTHENTICATION POLICIES` | `CORTEX SEARCH SERVICES` | `DATA METRIC FUNCTIONS` | `DATASETS` | `DBT PROJECTS` | `DYNAMIC TABLES` | `EVENT TABLES` | `EXPERIMENTS` | `EXTERNAL TABLES` | `FILE FORMATS` | `FUNCTIONS` | `GIT REPOSITORIES` | `HYBRID TABLES` | `IMAGE REPOSITORIES` | `ICEBERG TABLES` | `INTERACTIVE TABLES` | `MASKING POLICIES` | `MATERIALIZED VIEWS` | `MCP SERVERS` | `MODELS` | `MODEL MONITORS` | `NETWORK RULES` | `NOTEBOOKS` | `ONLINE FEATURE TABLES` | `PACKAGES POLICIES` | `PASSWORD POLICIES` | `PIPES` | `PRIVACY POLICIES` | `PROCEDURES` | `PROJECTION POLICIES` | `ROW ACCESS POLICIES` | `SECRETS` | `SEMANTIC VIEWS` | `SERVICES` | `SESSION POLICIES` | `SEQUENCES` | `SNAPSHOTS` | `SNAPSHOT POLICIES` | `SNAPSHOT SETS` | `STAGES` | `STREAMS` | `STREAMLITS` | `TABLES` | `TAGS` | `TASKS` | `VIEWS` | `WORKSPACES`. Snowflake validates the type at apply time.
	ObjectTypePlural *string `json:"objectTypePlural,omitempty" tf:"object_type_plural,omitempty"`
}

type OnSchemaObjectInheritedParameters struct {

	// (Boolean) If true, the inherited privilege will be granted on all schemas in the account.
	// If true, the inherited privilege will be granted on all objects of the given type in the account.
	// +kubebuilder:validation:Optional
	InAccount *bool `json:"inAccount,omitempty" tf:"in_account,omitempty"`

	// (String) The fully qualified name of the database in which the inherited privilege will be granted on all schemas.
	// The fully qualified name of the database in which the inherited privilege will be granted on all objects of the given type.
	// +kubebuilder:validation:Optional
	InDatabase *string `json:"inDatabase,omitempty" tf:"in_database,omitempty"`

	// (String)
	// The fully qualified name of the schema in which the inherited privilege will be granted on all objects of the given type.
	// +kubebuilder:validation:Optional
	InSchema *string `json:"inSchema,omitempty" tf:"in_schema,omitempty"`

	// insensitive): USERS | RESOURCE MONITORS | WAREHOUSES | COMPUTE POOLS | DATABASES | INTEGRATIONS | CONNECTIONS | FAILOVER GROUPS | REPLICATION GROUPS | EXTERNAL VOLUMES. Snowflake validates the type at apply time.
	// The plural object type of the schema object on which an inherited privilege will be granted. For more information head over to [Snowflake documentation](https://docs.snowflake.com/en/sql-reference/sql/grant-privilege#required-parameters). Known examples (case-insensitive): `AGENTS` | `AGGREGATION POLICIES` | `ALERTS` | `AUTHENTICATION POLICIES` | `CORTEX SEARCH SERVICES` | `DATA METRIC FUNCTIONS` | `DATASETS` | `DBT PROJECTS` | `DYNAMIC TABLES` | `EVENT TABLES` | `EXPERIMENTS` | `EXTERNAL TABLES` | `FILE FORMATS` | `FUNCTIONS` | `GIT REPOSITORIES` | `HYBRID TABLES` | `IMAGE REPOSITORIES` | `ICEBERG TABLES` | `INTERACTIVE TABLES` | `MASKING POLICIES` | `MATERIALIZED VIEWS` | `MCP SERVERS` | `MODELS` | `MODEL MONITORS` | `NETWORK RULES` | `NOTEBOOKS` | `ONLINE FEATURE TABLES` | `PACKAGES POLICIES` | `PASSWORD POLICIES` | `PIPES` | `PRIVACY POLICIES` | `PROCEDURES` | `PROJECTION POLICIES` | `ROW ACCESS POLICIES` | `SECRETS` | `SEMANTIC VIEWS` | `SERVICES` | `SESSION POLICIES` | `SEQUENCES` | `SNAPSHOTS` | `SNAPSHOT POLICIES` | `SNAPSHOT SETS` | `STAGES` | `STREAMS` | `STREAMLITS` | `TABLES` | `TAGS` | `TASKS` | `VIEWS` | `WORKSPACES`. Snowflake validates the type at apply time.
	// +kubebuilder:validation:Optional
	ObjectTypePlural *string `json:"objectTypePlural" tf:"object_type_plural,omitempty"`
}

type OnSchemaObjectInitParameters struct {

	// (Block List, Max: 1) Configures the privilege to be granted on all objects in either a database or schema. (see below for nested schema)
	// Configures the privilege to be granted on all objects in either a database or schema.
	All []AllInitParameters `json:"all,omitempty" tf:"all,omitempty"`

	// (Block List, Max: 1) Configures the privilege to be granted on future objects in either a database or schema. (see below for nested schema)
	// Configures the privilege to be granted on future objects in either a database or schema.
	Future []FutureInitParameters `json:"future,omitempty" tf:"future,omitempty"`

	// (Block List, Max: 1) Configures an inherited privilege to be granted on all current and future account objects of a given type in the account. See Inherited grants for more details. This field can be only used when INHERITED_GRANTS option is specified in provider block in the experimental_features_enabled field. (see below for nested schema)
	// Configures an inherited privilege to be granted on all current and future objects of a given type in the account, a database, or a schema. See [Inherited grants](https://docs.snowflake.com/en/user-guide/inherited-grants-using) for more details. This field can be only used when `INHERITED_GRANTS` option is specified in provider block in the [`experimental_features_enabled`](../#experimental_features_enabled-1) field.
	Inherited []OnSchemaObjectInheritedInitParameters `json:"inherited,omitempty" tf:"inherited,omitempty"`

	// (String) The fully qualified name of the object on which privileges will be granted.
	// The fully qualified name of the object on which privileges will be granted.
	ObjectName *string `json:"objectName,omitempty" tf:"object_name,omitempty"`

	// insensitive): USER | RESOURCE MONITOR | WAREHOUSE | COMPUTE POOL | DATABASE | INTEGRATION | CONNECTION | FAILOVER GROUP | REPLICATION GROUP | EXTERNAL VOLUME | SNOWFLAKE INTELLIGENCE. Snowflake validates the type at apply time.
	// The object type of the schema object on which privileges will be granted. For more information head over to [Snowflake documentation](https://docs.snowflake.com/en/sql-reference/sql/grant-privilege#required-parameters). Known examples (case-insensitive): `AGENT` | `AGGREGATION POLICY` | `ALERT` | `AUTHENTICATION POLICY` | `CORTEX SEARCH SERVICE` | `DATA METRIC FUNCTION` | `DATASET` | `DBT PROJECT` | `DYNAMIC TABLE` | `EVENT TABLE` | `EXPERIMENT` | `EXTERNAL TABLE` | `FILE FORMAT` | `FUNCTION` | `GATEWAY` | `GIT REPOSITORY` | `HYBRID TABLE` | `IMAGE REPOSITORY` | `ICEBERG TABLE` | `INTERACTIVE TABLE` | `JOIN POLICY` | `MASKING POLICY` | `MATERIALIZED VIEW` | `MCP SERVER` | `MODEL` | `MODEL MONITOR` | `NETWORK RULE` | `NOTEBOOK` | `NOTEBOOK PROJECT` | `ONLINE FEATURE TABLE` | `PACKAGES POLICY` | `PASSWORD POLICY` | `PIPE` | `PRIVACY POLICY` | `PROCEDURE` | `PROJECTION POLICY` | `ROW ACCESS POLICY` | `SECRET` | `SEMANTIC VIEW` | `SERVICE` | `SESSION POLICY` | `SEQUENCE` | `SNAPSHOT` | `SNAPSHOT POLICY` | `SNAPSHOT SET` | `STAGE` | `STORAGE LIFECYCLE POLICY` | `STREAM` | `STREAMLIT` | `TABLE` | `TAG` | `TASK` | `VIEW` | `WORKSPACE`. Snowflake validates the type at apply time.
	ObjectType *string `json:"objectType,omitempty" tf:"object_type,omitempty"`
}

type OnSchemaObjectObservation struct {

	// (Block List, Max: 1) Configures the privilege to be granted on all objects in either a database or schema. (see below for nested schema)
	// Configures the privilege to be granted on all objects in either a database or schema.
	All []AllObservation `json:"all,omitempty" tf:"all,omitempty"`

	// (Block List, Max: 1) Configures the privilege to be granted on future objects in either a database or schema. (see below for nested schema)
	// Configures the privilege to be granted on future objects in either a database or schema.
	Future []FutureObservation `json:"future,omitempty" tf:"future,omitempty"`

	// (Block List, Max: 1) Configures an inherited privilege to be granted on all current and future account objects of a given type in the account. See Inherited grants for more details. This field can be only used when INHERITED_GRANTS option is specified in provider block in the experimental_features_enabled field. (see below for nested schema)
	// Configures an inherited privilege to be granted on all current and future objects of a given type in the account, a database, or a schema. See [Inherited grants](https://docs.snowflake.com/en/user-guide/inherited-grants-using) for more details. This field can be only used when `INHERITED_GRANTS` option is specified in provider block in the [`experimental_features_enabled`](../#experimental_features_enabled-1) field.
	Inherited []OnSchemaObjectInheritedObservation `json:"inherited,omitempty" tf:"inherited,omitempty"`

	// (String) The fully qualified name of the object on which privileges will be granted.
	// The fully qualified name of the object on which privileges will be granted.
	ObjectName *string `json:"objectName,omitempty" tf:"object_name,omitempty"`

	// insensitive): USER | RESOURCE MONITOR | WAREHOUSE | COMPUTE POOL | DATABASE | INTEGRATION | CONNECTION | FAILOVER GROUP | REPLICATION GROUP | EXTERNAL VOLUME | SNOWFLAKE INTELLIGENCE. Snowflake validates the type at apply time.
	// The object type of the schema object on which privileges will be granted. For more information head over to [Snowflake documentation](https://docs.snowflake.com/en/sql-reference/sql/grant-privilege#required-parameters). Known examples (case-insensitive): `AGENT` | `AGGREGATION POLICY` | `ALERT` | `AUTHENTICATION POLICY` | `CORTEX SEARCH SERVICE` | `DATA METRIC FUNCTION` | `DATASET` | `DBT PROJECT` | `DYNAMIC TABLE` | `EVENT TABLE` | `EXPERIMENT` | `EXTERNAL TABLE` | `FILE FORMAT` | `FUNCTION` | `GATEWAY` | `GIT REPOSITORY` | `HYBRID TABLE` | `IMAGE REPOSITORY` | `ICEBERG TABLE` | `INTERACTIVE TABLE` | `JOIN POLICY` | `MASKING POLICY` | `MATERIALIZED VIEW` | `MCP SERVER` | `MODEL` | `MODEL MONITOR` | `NETWORK RULE` | `NOTEBOOK` | `NOTEBOOK PROJECT` | `ONLINE FEATURE TABLE` | `PACKAGES POLICY` | `PASSWORD POLICY` | `PIPE` | `PRIVACY POLICY` | `PROCEDURE` | `PROJECTION POLICY` | `ROW ACCESS POLICY` | `SECRET` | `SEMANTIC VIEW` | `SERVICE` | `SESSION POLICY` | `SEQUENCE` | `SNAPSHOT` | `SNAPSHOT POLICY` | `SNAPSHOT SET` | `STAGE` | `STORAGE LIFECYCLE POLICY` | `STREAM` | `STREAMLIT` | `TABLE` | `TAG` | `TASK` | `VIEW` | `WORKSPACE`. Snowflake validates the type at apply time.
	ObjectType *string `json:"objectType,omitempty" tf:"object_type,omitempty"`
}

type OnSchemaObjectParameters struct {

	// (Block List, Max: 1) Configures the privilege to be granted on all objects in either a database or schema. (see below for nested schema)
	// Configures the privilege to be granted on all objects in either a database or schema.
	// +kubebuilder:validation:Optional
	All []AllParameters `json:"all,omitempty" tf:"all,omitempty"`

	// (Block List, Max: 1) Configures the privilege to be granted on future objects in either a database or schema. (see below for nested schema)
	// Configures the privilege to be granted on future objects in either a database or schema.
	// +kubebuilder:validation:Optional
	Future []FutureParameters `json:"future,omitempty" tf:"future,omitempty"`

	// (Block List, Max: 1) Configures an inherited privilege to be granted on all current and future account objects of a given type in the account. See Inherited grants for more details. This field can be only used when INHERITED_GRANTS option is specified in provider block in the experimental_features_enabled field. (see below for nested schema)
	// Configures an inherited privilege to be granted on all current and future objects of a given type in the account, a database, or a schema. See [Inherited grants](https://docs.snowflake.com/en/user-guide/inherited-grants-using) for more details. This field can be only used when `INHERITED_GRANTS` option is specified in provider block in the [`experimental_features_enabled`](../#experimental_features_enabled-1) field.
	// +kubebuilder:validation:Optional
	Inherited []OnSchemaObjectInheritedParameters `json:"inherited,omitempty" tf:"inherited,omitempty"`

	// (String) The fully qualified name of the object on which privileges will be granted.
	// The fully qualified name of the object on which privileges will be granted.
	// +kubebuilder:validation:Optional
	ObjectName *string `json:"objectName,omitempty" tf:"object_name,omitempty"`

	// insensitive): USER | RESOURCE MONITOR | WAREHOUSE | COMPUTE POOL | DATABASE | INTEGRATION | CONNECTION | FAILOVER GROUP | REPLICATION GROUP | EXTERNAL VOLUME | SNOWFLAKE INTELLIGENCE. Snowflake validates the type at apply time.
	// The object type of the schema object on which privileges will be granted. For more information head over to [Snowflake documentation](https://docs.snowflake.com/en/sql-reference/sql/grant-privilege#required-parameters). Known examples (case-insensitive): `AGENT` | `AGGREGATION POLICY` | `ALERT` | `AUTHENTICATION POLICY` | `CORTEX SEARCH SERVICE` | `DATA METRIC FUNCTION` | `DATASET` | `DBT PROJECT` | `DYNAMIC TABLE` | `EVENT TABLE` | `EXPERIMENT` | `EXTERNAL TABLE` | `FILE FORMAT` | `FUNCTION` | `GATEWAY` | `GIT REPOSITORY` | `HYBRID TABLE` | `IMAGE REPOSITORY` | `ICEBERG TABLE` | `INTERACTIVE TABLE` | `JOIN POLICY` | `MASKING POLICY` | `MATERIALIZED VIEW` | `MCP SERVER` | `MODEL` | `MODEL MONITOR` | `NETWORK RULE` | `NOTEBOOK` | `NOTEBOOK PROJECT` | `ONLINE FEATURE TABLE` | `PACKAGES POLICY` | `PASSWORD POLICY` | `PIPE` | `PRIVACY POLICY` | `PROCEDURE` | `PROJECTION POLICY` | `ROW ACCESS POLICY` | `SECRET` | `SEMANTIC VIEW` | `SERVICE` | `SESSION POLICY` | `SEQUENCE` | `SNAPSHOT` | `SNAPSHOT POLICY` | `SNAPSHOT SET` | `STAGE` | `STORAGE LIFECYCLE POLICY` | `STREAM` | `STREAMLIT` | `TABLE` | `TAG` | `TASK` | `VIEW` | `WORKSPACE`. Snowflake validates the type at apply time.
	// +kubebuilder:validation:Optional
	ObjectType *string `json:"objectType,omitempty" tf:"object_type,omitempty"`
}

type OnSchemaObservation struct {

	// (String) The fully qualified name of the database.
	// The fully qualified name of the database.
	AllSchemasInDatabase *string `json:"allSchemasInDatabase,omitempty" tf:"all_schemas_in_database,omitempty"`

	// (String) The fully qualified name of the database.
	// The fully qualified name of the database.
	FutureSchemasInDatabase *string `json:"futureSchemasInDatabase,omitempty" tf:"future_schemas_in_database,omitempty"`

	// (Block List, Max: 1) Configures an inherited privilege to be granted on all current and future account objects of a given type in the account. See Inherited grants for more details. This field can be only used when INHERITED_GRANTS option is specified in provider block in the experimental_features_enabled field. (see below for nested schema)
	// Configures an inherited privilege to be granted on all current and future schemas in either the account or a database. See [Inherited grants](https://docs.snowflake.com/en/user-guide/inherited-grants-using) for more details. This field can be only used when `INHERITED_GRANTS` option is specified in provider block in the [`experimental_features_enabled`](../#experimental_features_enabled-1) field.
	Inherited []OnSchemaInheritedObservation `json:"inherited,omitempty" tf:"inherited,omitempty"`

	// (String) The fully qualified name of the schema.
	// The fully qualified name of the schema.
	SchemaName *string `json:"schemaName,omitempty" tf:"schema_name,omitempty"`
}

type OnSchemaParameters struct {

	// (String) The fully qualified name of the database.
	// The fully qualified name of the database.
	// +kubebuilder:validation:Optional
	AllSchemasInDatabase *string `json:"allSchemasInDatabase,omitempty" tf:"all_schemas_in_database,omitempty"`

	// (String) The fully qualified name of the database.
	// The fully qualified name of the database.
	// +kubebuilder:validation:Optional
	FutureSchemasInDatabase *string `json:"futureSchemasInDatabase,omitempty" tf:"future_schemas_in_database,omitempty"`

	// (Block List, Max: 1) Configures an inherited privilege to be granted on all current and future account objects of a given type in the account. See Inherited grants for more details. This field can be only used when INHERITED_GRANTS option is specified in provider block in the experimental_features_enabled field. (see below for nested schema)
	// Configures an inherited privilege to be granted on all current and future schemas in either the account or a database. See [Inherited grants](https://docs.snowflake.com/en/user-guide/inherited-grants-using) for more details. This field can be only used when `INHERITED_GRANTS` option is specified in provider block in the [`experimental_features_enabled`](../#experimental_features_enabled-1) field.
	// +kubebuilder:validation:Optional
	Inherited []OnSchemaInheritedParameters `json:"inherited,omitempty" tf:"inherited,omitempty"`

	// (String) The fully qualified name of the schema.
	// The fully qualified name of the schema.
	// +kubebuilder:validation:Optional
	SchemaName *string `json:"schemaName,omitempty" tf:"schema_name,omitempty"`
}

// AccountRolePrivilegeGrantSpec defines the desired state of AccountRolePrivilegeGrant
type AccountRolePrivilegeGrantSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     AccountRolePrivilegeGrantParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider AccountRolePrivilegeGrantInitParameters `json:"initProvider,omitempty"`
}

// AccountRolePrivilegeGrantStatus defines the observed state of AccountRolePrivilegeGrant.
type AccountRolePrivilegeGrantStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        AccountRolePrivilegeGrantObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// AccountRolePrivilegeGrant is the Schema for the AccountRolePrivilegeGrants API.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,snowflake}
type AccountRolePrivilegeGrant struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              AccountRolePrivilegeGrantSpec   `json:"spec"`
	Status            AccountRolePrivilegeGrantStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// AccountRolePrivilegeGrantList contains a list of AccountRolePrivilegeGrants
type AccountRolePrivilegeGrantList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []AccountRolePrivilegeGrant `json:"items"`
}

// Repository type metadata.
var (
	AccountRolePrivilegeGrant_Kind             = "AccountRolePrivilegeGrant"
	AccountRolePrivilegeGrant_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: AccountRolePrivilegeGrant_Kind}.String()
	AccountRolePrivilegeGrant_KindAPIVersion   = AccountRolePrivilegeGrant_Kind + "." + CRDGroupVersion.String()
	AccountRolePrivilegeGrant_GroupVersionKind = CRDGroupVersion.WithKind(AccountRolePrivilegeGrant_Kind)
)

func init() {
	SchemeBuilder.Register(&AccountRolePrivilegeGrant{}, &AccountRolePrivilegeGrantList{})
}
