// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by angryjet. DO NOT EDIT.

package v1alpha1

import (
	"context"
	v1alpha1 "github.com/BronzeDeer/provider-snowflake/apis/cluster/warehouse/v1alpha1"
	reference "github.com/crossplane/crossplane-runtime/v2/pkg/reference"
	errors "github.com/pkg/errors"
	client "sigs.k8s.io/controller-runtime/pkg/client"
)

// ResolveReferences of this User.
func (mg *User) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.DefaultRole),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.DefaultRoleRef,
		Selector:     mg.Spec.ForProvider.DefaultRoleSelector,
		To: reference.To{
			List:    &AccountRoleList{},
			Managed: &AccountRole{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.DefaultRole")
	}
	mg.Spec.ForProvider.DefaultRole = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.DefaultRoleRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.DefaultWarehouse),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.DefaultWarehouseRef,
		Selector:     mg.Spec.ForProvider.DefaultWarehouseSelector,
		To: reference.To{
			List:    &v1alpha1.WarehouseList{},
			Managed: &v1alpha1.Warehouse{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.DefaultWarehouse")
	}
	mg.Spec.ForProvider.DefaultWarehouse = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.DefaultWarehouseRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.DefaultRole),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.DefaultRoleRef,
		Selector:     mg.Spec.InitProvider.DefaultRoleSelector,
		To: reference.To{
			List:    &AccountRoleList{},
			Managed: &AccountRole{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.DefaultRole")
	}
	mg.Spec.InitProvider.DefaultRole = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.DefaultRoleRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.DefaultWarehouse),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.DefaultWarehouseRef,
		Selector:     mg.Spec.InitProvider.DefaultWarehouseSelector,
		To: reference.To{
			List:    &v1alpha1.WarehouseList{},
			Managed: &v1alpha1.Warehouse{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.DefaultWarehouse")
	}
	mg.Spec.InitProvider.DefaultWarehouse = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.DefaultWarehouseRef = rsp.ResolvedReference

	return nil
}
