//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArgumentsInitParameters) DeepCopyInto(out *ArgumentsInitParameters) {
	*out = *in
	if in.ArgDataType != nil {
		in, out := &in.ArgDataType, &out.ArgDataType
		*out = new(string)
		**out = **in
	}
	if in.ArgDefaultValue != nil {
		in, out := &in.ArgDefaultValue, &out.ArgDefaultValue
		*out = new(string)
		**out = **in
	}
	if in.ArgName != nil {
		in, out := &in.ArgName, &out.ArgName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArgumentsInitParameters.
func (in *ArgumentsInitParameters) DeepCopy() *ArgumentsInitParameters {
	if in == nil {
		return nil
	}
	out := new(ArgumentsInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArgumentsObservation) DeepCopyInto(out *ArgumentsObservation) {
	*out = *in
	if in.ArgDataType != nil {
		in, out := &in.ArgDataType, &out.ArgDataType
		*out = new(string)
		**out = **in
	}
	if in.ArgDefaultValue != nil {
		in, out := &in.ArgDefaultValue, &out.ArgDefaultValue
		*out = new(string)
		**out = **in
	}
	if in.ArgName != nil {
		in, out := &in.ArgName, &out.ArgName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArgumentsObservation.
func (in *ArgumentsObservation) DeepCopy() *ArgumentsObservation {
	if in == nil {
		return nil
	}
	out := new(ArgumentsObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArgumentsParameters) DeepCopyInto(out *ArgumentsParameters) {
	*out = *in
	if in.ArgDataType != nil {
		in, out := &in.ArgDataType, &out.ArgDataType
		*out = new(string)
		**out = **in
	}
	if in.ArgDefaultValue != nil {
		in, out := &in.ArgDefaultValue, &out.ArgDefaultValue
		*out = new(string)
		**out = **in
	}
	if in.ArgName != nil {
		in, out := &in.ArgName, &out.ArgName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArgumentsParameters.
func (in *ArgumentsParameters) DeepCopy() *ArgumentsParameters {
	if in == nil {
		return nil
	}
	out := new(ArgumentsParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnableConsoleOutputInitParameters) DeepCopyInto(out *EnableConsoleOutputInitParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnableConsoleOutputInitParameters.
func (in *EnableConsoleOutputInitParameters) DeepCopy() *EnableConsoleOutputInitParameters {
	if in == nil {
		return nil
	}
	out := new(EnableConsoleOutputInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnableConsoleOutputObservation) DeepCopyInto(out *EnableConsoleOutputObservation) {
	*out = *in
	if in.Default != nil {
		in, out := &in.Default, &out.Default
		*out = new(string)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.Key != nil {
		in, out := &in.Key, &out.Key
		*out = new(string)
		**out = **in
	}
	if in.Level != nil {
		in, out := &in.Level, &out.Level
		*out = new(string)
		**out = **in
	}
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnableConsoleOutputObservation.
func (in *EnableConsoleOutputObservation) DeepCopy() *EnableConsoleOutputObservation {
	if in == nil {
		return nil
	}
	out := new(EnableConsoleOutputObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnableConsoleOutputParameters) DeepCopyInto(out *EnableConsoleOutputParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnableConsoleOutputParameters.
func (in *EnableConsoleOutputParameters) DeepCopy() *EnableConsoleOutputParameters {
	if in == nil {
		return nil
	}
	out := new(EnableConsoleOutputParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImportsInitParameters) DeepCopyInto(out *ImportsInitParameters) {
	*out = *in
	if in.PathOnStage != nil {
		in, out := &in.PathOnStage, &out.PathOnStage
		*out = new(string)
		**out = **in
	}
	if in.StageLocation != nil {
		in, out := &in.StageLocation, &out.StageLocation
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImportsInitParameters.
func (in *ImportsInitParameters) DeepCopy() *ImportsInitParameters {
	if in == nil {
		return nil
	}
	out := new(ImportsInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImportsObservation) DeepCopyInto(out *ImportsObservation) {
	*out = *in
	if in.PathOnStage != nil {
		in, out := &in.PathOnStage, &out.PathOnStage
		*out = new(string)
		**out = **in
	}
	if in.StageLocation != nil {
		in, out := &in.StageLocation, &out.StageLocation
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImportsObservation.
func (in *ImportsObservation) DeepCopy() *ImportsObservation {
	if in == nil {
		return nil
	}
	out := new(ImportsObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImportsParameters) DeepCopyInto(out *ImportsParameters) {
	*out = *in
	if in.PathOnStage != nil {
		in, out := &in.PathOnStage, &out.PathOnStage
		*out = new(string)
		**out = **in
	}
	if in.StageLocation != nil {
		in, out := &in.StageLocation, &out.StageLocation
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImportsParameters.
func (in *ImportsParameters) DeepCopy() *ImportsParameters {
	if in == nil {
		return nil
	}
	out := new(ImportsParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LogEventLevelInitParameters) DeepCopyInto(out *LogEventLevelInitParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LogEventLevelInitParameters.
func (in *LogEventLevelInitParameters) DeepCopy() *LogEventLevelInitParameters {
	if in == nil {
		return nil
	}
	out := new(LogEventLevelInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LogEventLevelObservation) DeepCopyInto(out *LogEventLevelObservation) {
	*out = *in
	if in.Default != nil {
		in, out := &in.Default, &out.Default
		*out = new(string)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.Key != nil {
		in, out := &in.Key, &out.Key
		*out = new(string)
		**out = **in
	}
	if in.Level != nil {
		in, out := &in.Level, &out.Level
		*out = new(string)
		**out = **in
	}
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LogEventLevelObservation.
func (in *LogEventLevelObservation) DeepCopy() *LogEventLevelObservation {
	if in == nil {
		return nil
	}
	out := new(LogEventLevelObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LogEventLevelParameters) DeepCopyInto(out *LogEventLevelParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LogEventLevelParameters.
func (in *LogEventLevelParameters) DeepCopy() *LogEventLevelParameters {
	if in == nil {
		return nil
	}
	out := new(LogEventLevelParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LogLevelInitParameters) DeepCopyInto(out *LogLevelInitParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LogLevelInitParameters.
func (in *LogLevelInitParameters) DeepCopy() *LogLevelInitParameters {
	if in == nil {
		return nil
	}
	out := new(LogLevelInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LogLevelObservation) DeepCopyInto(out *LogLevelObservation) {
	*out = *in
	if in.Default != nil {
		in, out := &in.Default, &out.Default
		*out = new(string)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.Key != nil {
		in, out := &in.Key, &out.Key
		*out = new(string)
		**out = **in
	}
	if in.Level != nil {
		in, out := &in.Level, &out.Level
		*out = new(string)
		**out = **in
	}
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LogLevelObservation.
func (in *LogLevelObservation) DeepCopy() *LogLevelObservation {
	if in == nil {
		return nil
	}
	out := new(LogLevelObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LogLevelParameters) DeepCopyInto(out *LogLevelParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LogLevelParameters.
func (in *LogLevelParameters) DeepCopy() *LogLevelParameters {
	if in == nil {
		return nil
	}
	out := new(LogLevelParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MetricLevelInitParameters) DeepCopyInto(out *MetricLevelInitParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MetricLevelInitParameters.
func (in *MetricLevelInitParameters) DeepCopy() *MetricLevelInitParameters {
	if in == nil {
		return nil
	}
	out := new(MetricLevelInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MetricLevelObservation) DeepCopyInto(out *MetricLevelObservation) {
	*out = *in
	if in.Default != nil {
		in, out := &in.Default, &out.Default
		*out = new(string)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.Key != nil {
		in, out := &in.Key, &out.Key
		*out = new(string)
		**out = **in
	}
	if in.Level != nil {
		in, out := &in.Level, &out.Level
		*out = new(string)
		**out = **in
	}
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MetricLevelObservation.
func (in *MetricLevelObservation) DeepCopy() *MetricLevelObservation {
	if in == nil {
		return nil
	}
	out := new(MetricLevelObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MetricLevelParameters) DeepCopyInto(out *MetricLevelParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MetricLevelParameters.
func (in *MetricLevelParameters) DeepCopy() *MetricLevelParameters {
	if in == nil {
		return nil
	}
	out := new(MetricLevelParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ParametersInitParameters) DeepCopyInto(out *ParametersInitParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ParametersInitParameters.
func (in *ParametersInitParameters) DeepCopy() *ParametersInitParameters {
	if in == nil {
		return nil
	}
	out := new(ParametersInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ParametersObservation) DeepCopyInto(out *ParametersObservation) {
	*out = *in
	if in.EnableConsoleOutput != nil {
		in, out := &in.EnableConsoleOutput, &out.EnableConsoleOutput
		*out = make([]EnableConsoleOutputObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LogEventLevel != nil {
		in, out := &in.LogEventLevel, &out.LogEventLevel
		*out = make([]LogEventLevelObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LogLevel != nil {
		in, out := &in.LogLevel, &out.LogLevel
		*out = make([]LogLevelObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.MetricLevel != nil {
		in, out := &in.MetricLevel, &out.MetricLevel
		*out = make([]MetricLevelObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.TraceLevel != nil {
		in, out := &in.TraceLevel, &out.TraceLevel
		*out = make([]TraceLevelObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ParametersObservation.
func (in *ParametersObservation) DeepCopy() *ParametersObservation {
	if in == nil {
		return nil
	}
	out := new(ParametersObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ParametersParameters) DeepCopyInto(out *ParametersParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ParametersParameters.
func (in *ParametersParameters) DeepCopy() *ParametersParameters {
	if in == nil {
		return nil
	}
	out := new(ParametersParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProcedurePython) DeepCopyInto(out *ProcedurePython) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProcedurePython.
func (in *ProcedurePython) DeepCopy() *ProcedurePython {
	if in == nil {
		return nil
	}
	out := new(ProcedurePython)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ProcedurePython) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProcedurePythonInitParameters) DeepCopyInto(out *ProcedurePythonInitParameters) {
	*out = *in
	if in.Arguments != nil {
		in, out := &in.Arguments, &out.Arguments
		*out = make([]ArgumentsInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Comment != nil {
		in, out := &in.Comment, &out.Comment
		*out = new(string)
		**out = **in
	}
	if in.Database != nil {
		in, out := &in.Database, &out.Database
		*out = new(string)
		**out = **in
	}
	if in.DatabaseRef != nil {
		in, out := &in.DatabaseRef, &out.DatabaseRef
		*out = new(v1.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.DatabaseSelector != nil {
		in, out := &in.DatabaseSelector, &out.DatabaseSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.EnableConsoleOutput != nil {
		in, out := &in.EnableConsoleOutput, &out.EnableConsoleOutput
		*out = new(bool)
		**out = **in
	}
	if in.ExecuteAs != nil {
		in, out := &in.ExecuteAs, &out.ExecuteAs
		*out = new(string)
		**out = **in
	}
	if in.ExternalAccessIntegrations != nil {
		in, out := &in.ExternalAccessIntegrations, &out.ExternalAccessIntegrations
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Handler != nil {
		in, out := &in.Handler, &out.Handler
		*out = new(string)
		**out = **in
	}
	if in.Imports != nil {
		in, out := &in.Imports, &out.Imports
		*out = make([]ImportsInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.IsSecure != nil {
		in, out := &in.IsSecure, &out.IsSecure
		*out = new(string)
		**out = **in
	}
	if in.LogEventLevel != nil {
		in, out := &in.LogEventLevel, &out.LogEventLevel
		*out = new(string)
		**out = **in
	}
	if in.LogLevel != nil {
		in, out := &in.LogLevel, &out.LogLevel
		*out = new(string)
		**out = **in
	}
	if in.MetricLevel != nil {
		in, out := &in.MetricLevel, &out.MetricLevel
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.NullInputBehavior != nil {
		in, out := &in.NullInputBehavior, &out.NullInputBehavior
		*out = new(string)
		**out = **in
	}
	if in.Packages != nil {
		in, out := &in.Packages, &out.Packages
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.ProcedureDefinition != nil {
		in, out := &in.ProcedureDefinition, &out.ProcedureDefinition
		*out = new(string)
		**out = **in
	}
	if in.ReturnType != nil {
		in, out := &in.ReturnType, &out.ReturnType
		*out = new(string)
		**out = **in
	}
	if in.RuntimeVersion != nil {
		in, out := &in.RuntimeVersion, &out.RuntimeVersion
		*out = new(string)
		**out = **in
	}
	if in.Schema != nil {
		in, out := &in.Schema, &out.Schema
		*out = new(string)
		**out = **in
	}
	if in.SchemaRef != nil {
		in, out := &in.SchemaRef, &out.SchemaRef
		*out = new(v1.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.SchemaSelector != nil {
		in, out := &in.SchemaSelector, &out.SchemaSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.Secrets != nil {
		in, out := &in.Secrets, &out.Secrets
		*out = make([]SecretsInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.SnowparkPackage != nil {
		in, out := &in.SnowparkPackage, &out.SnowparkPackage
		*out = new(string)
		**out = **in
	}
	if in.TraceLevel != nil {
		in, out := &in.TraceLevel, &out.TraceLevel
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProcedurePythonInitParameters.
func (in *ProcedurePythonInitParameters) DeepCopy() *ProcedurePythonInitParameters {
	if in == nil {
		return nil
	}
	out := new(ProcedurePythonInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProcedurePythonList) DeepCopyInto(out *ProcedurePythonList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ProcedurePython, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProcedurePythonList.
func (in *ProcedurePythonList) DeepCopy() *ProcedurePythonList {
	if in == nil {
		return nil
	}
	out := new(ProcedurePythonList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ProcedurePythonList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProcedurePythonObservation) DeepCopyInto(out *ProcedurePythonObservation) {
	*out = *in
	if in.Arguments != nil {
		in, out := &in.Arguments, &out.Arguments
		*out = make([]ArgumentsObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Comment != nil {
		in, out := &in.Comment, &out.Comment
		*out = new(string)
		**out = **in
	}
	if in.Database != nil {
		in, out := &in.Database, &out.Database
		*out = new(string)
		**out = **in
	}
	if in.EnableConsoleOutput != nil {
		in, out := &in.EnableConsoleOutput, &out.EnableConsoleOutput
		*out = new(bool)
		**out = **in
	}
	if in.ExecuteAs != nil {
		in, out := &in.ExecuteAs, &out.ExecuteAs
		*out = new(string)
		**out = **in
	}
	if in.ExternalAccessIntegrations != nil {
		in, out := &in.ExternalAccessIntegrations, &out.ExternalAccessIntegrations
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.FullyQualifiedName != nil {
		in, out := &in.FullyQualifiedName, &out.FullyQualifiedName
		*out = new(string)
		**out = **in
	}
	if in.Handler != nil {
		in, out := &in.Handler, &out.Handler
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.Imports != nil {
		in, out := &in.Imports, &out.Imports
		*out = make([]ImportsObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.IsSecure != nil {
		in, out := &in.IsSecure, &out.IsSecure
		*out = new(string)
		**out = **in
	}
	if in.LogEventLevel != nil {
		in, out := &in.LogEventLevel, &out.LogEventLevel
		*out = new(string)
		**out = **in
	}
	if in.LogLevel != nil {
		in, out := &in.LogLevel, &out.LogLevel
		*out = new(string)
		**out = **in
	}
	if in.MetricLevel != nil {
		in, out := &in.MetricLevel, &out.MetricLevel
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.NullInputBehavior != nil {
		in, out := &in.NullInputBehavior, &out.NullInputBehavior
		*out = new(string)
		**out = **in
	}
	if in.Packages != nil {
		in, out := &in.Packages, &out.Packages
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Parameters != nil {
		in, out := &in.Parameters, &out.Parameters
		*out = make([]ParametersObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ProcedureDefinition != nil {
		in, out := &in.ProcedureDefinition, &out.ProcedureDefinition
		*out = new(string)
		**out = **in
	}
	if in.ProcedureLanguage != nil {
		in, out := &in.ProcedureLanguage, &out.ProcedureLanguage
		*out = new(string)
		**out = **in
	}
	if in.ReturnType != nil {
		in, out := &in.ReturnType, &out.ReturnType
		*out = new(string)
		**out = **in
	}
	if in.RuntimeVersion != nil {
		in, out := &in.RuntimeVersion, &out.RuntimeVersion
		*out = new(string)
		**out = **in
	}
	if in.Schema != nil {
		in, out := &in.Schema, &out.Schema
		*out = new(string)
		**out = **in
	}
	if in.Secrets != nil {
		in, out := &in.Secrets, &out.Secrets
		*out = make([]SecretsObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ShowOutput != nil {
		in, out := &in.ShowOutput, &out.ShowOutput
		*out = make([]ShowOutputObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.SnowparkPackage != nil {
		in, out := &in.SnowparkPackage, &out.SnowparkPackage
		*out = new(string)
		**out = **in
	}
	if in.TraceLevel != nil {
		in, out := &in.TraceLevel, &out.TraceLevel
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProcedurePythonObservation.
func (in *ProcedurePythonObservation) DeepCopy() *ProcedurePythonObservation {
	if in == nil {
		return nil
	}
	out := new(ProcedurePythonObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProcedurePythonParameters) DeepCopyInto(out *ProcedurePythonParameters) {
	*out = *in
	if in.Arguments != nil {
		in, out := &in.Arguments, &out.Arguments
		*out = make([]ArgumentsParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Comment != nil {
		in, out := &in.Comment, &out.Comment
		*out = new(string)
		**out = **in
	}
	if in.Database != nil {
		in, out := &in.Database, &out.Database
		*out = new(string)
		**out = **in
	}
	if in.DatabaseRef != nil {
		in, out := &in.DatabaseRef, &out.DatabaseRef
		*out = new(v1.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.DatabaseSelector != nil {
		in, out := &in.DatabaseSelector, &out.DatabaseSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.EnableConsoleOutput != nil {
		in, out := &in.EnableConsoleOutput, &out.EnableConsoleOutput
		*out = new(bool)
		**out = **in
	}
	if in.ExecuteAs != nil {
		in, out := &in.ExecuteAs, &out.ExecuteAs
		*out = new(string)
		**out = **in
	}
	if in.ExternalAccessIntegrations != nil {
		in, out := &in.ExternalAccessIntegrations, &out.ExternalAccessIntegrations
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Handler != nil {
		in, out := &in.Handler, &out.Handler
		*out = new(string)
		**out = **in
	}
	if in.Imports != nil {
		in, out := &in.Imports, &out.Imports
		*out = make([]ImportsParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.IsSecure != nil {
		in, out := &in.IsSecure, &out.IsSecure
		*out = new(string)
		**out = **in
	}
	if in.LogEventLevel != nil {
		in, out := &in.LogEventLevel, &out.LogEventLevel
		*out = new(string)
		**out = **in
	}
	if in.LogLevel != nil {
		in, out := &in.LogLevel, &out.LogLevel
		*out = new(string)
		**out = **in
	}
	if in.MetricLevel != nil {
		in, out := &in.MetricLevel, &out.MetricLevel
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.NullInputBehavior != nil {
		in, out := &in.NullInputBehavior, &out.NullInputBehavior
		*out = new(string)
		**out = **in
	}
	if in.Packages != nil {
		in, out := &in.Packages, &out.Packages
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.ProcedureDefinition != nil {
		in, out := &in.ProcedureDefinition, &out.ProcedureDefinition
		*out = new(string)
		**out = **in
	}
	if in.ReturnType != nil {
		in, out := &in.ReturnType, &out.ReturnType
		*out = new(string)
		**out = **in
	}
	if in.RuntimeVersion != nil {
		in, out := &in.RuntimeVersion, &out.RuntimeVersion
		*out = new(string)
		**out = **in
	}
	if in.Schema != nil {
		in, out := &in.Schema, &out.Schema
		*out = new(string)
		**out = **in
	}
	if in.SchemaRef != nil {
		in, out := &in.SchemaRef, &out.SchemaRef
		*out = new(v1.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.SchemaSelector != nil {
		in, out := &in.SchemaSelector, &out.SchemaSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.Secrets != nil {
		in, out := &in.Secrets, &out.Secrets
		*out = make([]SecretsParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.SnowparkPackage != nil {
		in, out := &in.SnowparkPackage, &out.SnowparkPackage
		*out = new(string)
		**out = **in
	}
	if in.TraceLevel != nil {
		in, out := &in.TraceLevel, &out.TraceLevel
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProcedurePythonParameters.
func (in *ProcedurePythonParameters) DeepCopy() *ProcedurePythonParameters {
	if in == nil {
		return nil
	}
	out := new(ProcedurePythonParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProcedurePythonSpec) DeepCopyInto(out *ProcedurePythonSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProcedurePythonSpec.
func (in *ProcedurePythonSpec) DeepCopy() *ProcedurePythonSpec {
	if in == nil {
		return nil
	}
	out := new(ProcedurePythonSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProcedurePythonStatus) DeepCopyInto(out *ProcedurePythonStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProcedurePythonStatus.
func (in *ProcedurePythonStatus) DeepCopy() *ProcedurePythonStatus {
	if in == nil {
		return nil
	}
	out := new(ProcedurePythonStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretsInitParameters) DeepCopyInto(out *SecretsInitParameters) {
	*out = *in
	if in.SecretID != nil {
		in, out := &in.SecretID, &out.SecretID
		*out = new(string)
		**out = **in
	}
	if in.SecretVariableName != nil {
		in, out := &in.SecretVariableName, &out.SecretVariableName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretsInitParameters.
func (in *SecretsInitParameters) DeepCopy() *SecretsInitParameters {
	if in == nil {
		return nil
	}
	out := new(SecretsInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretsObservation) DeepCopyInto(out *SecretsObservation) {
	*out = *in
	if in.SecretID != nil {
		in, out := &in.SecretID, &out.SecretID
		*out = new(string)
		**out = **in
	}
	if in.SecretVariableName != nil {
		in, out := &in.SecretVariableName, &out.SecretVariableName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretsObservation.
func (in *SecretsObservation) DeepCopy() *SecretsObservation {
	if in == nil {
		return nil
	}
	out := new(SecretsObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretsParameters) DeepCopyInto(out *SecretsParameters) {
	*out = *in
	if in.SecretID != nil {
		in, out := &in.SecretID, &out.SecretID
		*out = new(string)
		**out = **in
	}
	if in.SecretVariableName != nil {
		in, out := &in.SecretVariableName, &out.SecretVariableName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretsParameters.
func (in *SecretsParameters) DeepCopy() *SecretsParameters {
	if in == nil {
		return nil
	}
	out := new(SecretsParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ShowOutputInitParameters) DeepCopyInto(out *ShowOutputInitParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ShowOutputInitParameters.
func (in *ShowOutputInitParameters) DeepCopy() *ShowOutputInitParameters {
	if in == nil {
		return nil
	}
	out := new(ShowOutputInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ShowOutputObservation) DeepCopyInto(out *ShowOutputObservation) {
	*out = *in
	if in.ArgumentsRaw != nil {
		in, out := &in.ArgumentsRaw, &out.ArgumentsRaw
		*out = new(string)
		**out = **in
	}
	if in.CatalogName != nil {
		in, out := &in.CatalogName, &out.CatalogName
		*out = new(string)
		**out = **in
	}
	if in.CreatedOn != nil {
		in, out := &in.CreatedOn, &out.CreatedOn
		*out = new(string)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.ExternalAccessIntegrations != nil {
		in, out := &in.ExternalAccessIntegrations, &out.ExternalAccessIntegrations
		*out = new(string)
		**out = **in
	}
	if in.IsAggregate != nil {
		in, out := &in.IsAggregate, &out.IsAggregate
		*out = new(bool)
		**out = **in
	}
	if in.IsAnsi != nil {
		in, out := &in.IsAnsi, &out.IsAnsi
		*out = new(bool)
		**out = **in
	}
	if in.IsBuiltin != nil {
		in, out := &in.IsBuiltin, &out.IsBuiltin
		*out = new(bool)
		**out = **in
	}
	if in.IsSecure != nil {
		in, out := &in.IsSecure, &out.IsSecure
		*out = new(bool)
		**out = **in
	}
	if in.IsTableFunction != nil {
		in, out := &in.IsTableFunction, &out.IsTableFunction
		*out = new(bool)
		**out = **in
	}
	if in.MaxNumArguments != nil {
		in, out := &in.MaxNumArguments, &out.MaxNumArguments
		*out = new(float64)
		**out = **in
	}
	if in.MinNumArguments != nil {
		in, out := &in.MinNumArguments, &out.MinNumArguments
		*out = new(float64)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.SchemaName != nil {
		in, out := &in.SchemaName, &out.SchemaName
		*out = new(string)
		**out = **in
	}
	if in.Secrets != nil {
		in, out := &in.Secrets, &out.Secrets
		*out = new(string)
		**out = **in
	}
	if in.ValidForClustering != nil {
		in, out := &in.ValidForClustering, &out.ValidForClustering
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ShowOutputObservation.
func (in *ShowOutputObservation) DeepCopy() *ShowOutputObservation {
	if in == nil {
		return nil
	}
	out := new(ShowOutputObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ShowOutputParameters) DeepCopyInto(out *ShowOutputParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ShowOutputParameters.
func (in *ShowOutputParameters) DeepCopy() *ShowOutputParameters {
	if in == nil {
		return nil
	}
	out := new(ShowOutputParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TraceLevelInitParameters) DeepCopyInto(out *TraceLevelInitParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TraceLevelInitParameters.
func (in *TraceLevelInitParameters) DeepCopy() *TraceLevelInitParameters {
	if in == nil {
		return nil
	}
	out := new(TraceLevelInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TraceLevelObservation) DeepCopyInto(out *TraceLevelObservation) {
	*out = *in
	if in.Default != nil {
		in, out := &in.Default, &out.Default
		*out = new(string)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.Key != nil {
		in, out := &in.Key, &out.Key
		*out = new(string)
		**out = **in
	}
	if in.Level != nil {
		in, out := &in.Level, &out.Level
		*out = new(string)
		**out = **in
	}
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TraceLevelObservation.
func (in *TraceLevelObservation) DeepCopy() *TraceLevelObservation {
	if in == nil {
		return nil
	}
	out := new(TraceLevelObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TraceLevelParameters) DeepCopyInto(out *TraceLevelParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TraceLevelParameters.
func (in *TraceLevelParameters) DeepCopy() *TraceLevelParameters {
	if in == nil {
		return nil
	}
	out := new(TraceLevelParameters)
	in.DeepCopyInto(out)
	return out
}
