name: PR integration tests

on:
  pull_request:
    types:
      - labeled
    branches:
      - main


jobs:
  create-test-account:
    if: ${{ contains( github.event.pull_request.labels.*.name, 'ok-to-test') && !contains( github.event.pull_request.labels.*.name, 'pr-account-deployed') }}
    permissions:
      id-token: write
      # FIXME: Is there anyway to restrict this to itself?
      pull-requests: write

    environment: int-test
    runs-on: ubuntu-24.04
    steps:
      - name: Show OIDC claims (right before assume)
        env:
          AUDIENCE: "snowflakecomputing.com"
        run: |
          TOKEN_JSON=$(curl -s -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=$AUDIENCE")
          ID_TOKEN=$(echo "$TOKEN_JSON" | jq -r .value)
          export ID_TOKEN_CONTENT=$(echo "$ID_TOKEN" | awk -F. '{print $2}' | base64 -d 2>/dev/null)
          echo $ID_TOKEN_CONTENT | jq -r
          export SUBJECT=$(echo $ID_TOKEN_CONTENT | jq -r .sub)
          echo "SUBJECT=$SUBJECT" >> $GITHUB_OUTPUT
          echo $SUBJECT
      - name: Show event
        run: |
          echo "${{ github.event.label.name }}"

      - uses: actions/checkout@v5
      - uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}


      - name: Restore and save Nix store
        uses: nix-community/cache-nix-action@v7
        with:
          # restore and save a cache using this key
          primary-key: nix-${{ runner.os }}-${{ hashFiles('**/*.nix', '**/flake.lock') }}
          # if there's no cache hit, restore a cache by this prefix
          restore-prefixes-first-match: nix-${{ runner.os }}-

      -
        name: setup
        uses: workflow/nix-shell-action@v4.0.0
        env:
          SNOWFLAKE_USER: ${{ vars.SNOWFLAKE_PR_ACC_MANAGER_USER }}
          SNOWFLAKE_ACCOUNT_NAME: ${{ vars.SNOWFLAKE_PR_ACC_MANAGER_ACCOUNT_NAME }}
          SNOWFLAKE_ROLE: ${{ vars.SNOWFLAKE_PR_ACC_MANAGER_ROLE }}
          SNOWFLAKE_HOST: ${{ vars.SNOWFLAKE_PR_ACC_MANAGER_HOST }}
        with:
          flakes-from-devshell: true
          script: |
            export SNOWFLAKE_PRIVATE_KEY_PATH="$(mktemp)"
            echo -n "${{ secrets.SNOWFLAKE_PR_ACC_MANAGER_PRIVATE_KEY }}" > $SNOWFLAKE_PRIVATE_KEY_PATH
            ./hack/ci/acc-isolation/scripts/setup-acc.sh ${{ github.event.number }}
        #shell: nix develop --impure --command "bash ${0}"

      - name: label-pr
        run: |
          curl -L \
            -X POST
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{github.token}}" \
            -H "X-GitHub-Api-Version: 2026-03-10" \
            https://api.github.com/repos/${{github.repository}}/issues/${{github.event.pull_request.number}}/labels \
            -d "$(yq ' . | to_entries | map(.key + ":" + .value) | . += "pr-account-deployed" | {"labels": .}' -o json --indent=0 pr-account.yaml)"

      # contains( github.event.pull_request.labels.*.name, 'My Label')
